name: myapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

 
dependencies:
  
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  cloud_firestore: ^4.17.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

 